import {
  UserProfile,
  SubmissionRecord,
  Squad,
  CuratedRoadmap,
  LeaderboardEntry,
  UnifiedSubmissionPayload,
} from "@/types";
import { calculateXp, calculateStreaks, getTodayDateStr } from "./habit-engine";

// Default Initial Demo Users
export const INITIAL_USER: UserProfile = {
  id: "user-1",
  name: "Nguyễn Văn Code",
  email: "coder@example.com",
  avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
  apiKey: "algo_live_8f3a9e120bc74921",
  currentStreak: 12,
  longestStreak: 28,
  lastActiveDate: getTodayDateStr(),
  totalXp: 1850,
  level: 6,
  streakFreeze: 2,
  dailyGoal: 1,
  joinedAt: "2024-01-15",
  handles: [
    {
      platform: "leetcode",
      handle: "tourist_lc",
      totalSolved: 142,
      easySolved: 58,
      mediumSolved: 72,
      hardSolved: 12,
      rankTitle: "Guardian",
      lastSyncedAt: new Date().toISOString(),
    },
    {
      platform: "codeforces",
      handle: "tourist",
      totalSolved: 85,
      rating: 1840,
      rankTitle: "Candidate Master",
      lastSyncedAt: new Date().toISOString(),
    },
  ],
};

export const INITIAL_SUBMISSIONS: SubmissionRecord[] = [
  {
    id: "sub-1",
    userId: "user-1",
    platform: "leetcode",
    problemId: "two-sum",
    problemTitle: "Two Sum",
    problemUrl: "https://leetcode.com/problems/two-sum/",
    difficulty: "EASY",
    tags: ["Array", "Hash Table"],
    language: "TypeScript",
    status: "ACCEPTED",
    xpEarned: 10,
    submittedAt: new Date().toISOString(),
  },
  {
    id: "sub-2",
    userId: "user-1",
    platform: "leetcode",
    problemId: "lru-cache",
    problemTitle: "LRU Cache",
    problemUrl: "https://leetcode.com/problems/lru-cache/",
    difficulty: "MEDIUM",
    tags: ["Hash Table", "Linked List", "Design"],
    language: "Go",
    status: "ACCEPTED",
    xpEarned: 25,
    submittedAt: new Date(Date.now() - 3600 * 1000 * 4).toISOString(),
  },
  {
    id: "sub-3",
    userId: "user-1",
    platform: "codeforces",
    problemId: "1850A",
    problemTitle: "To My Critics",
    problemUrl: "https://codeforces.com/problemset/problem/1850/A",
    difficulty: "EASY",
    rawDifficulty: "800",
    tags: ["brute force", "math"],
    language: "C++ 20",
    status: "ACCEPTED",
    xpEarned: 10,
    submittedAt: new Date(Date.now() - 3600 * 1000 * 24).toISOString(),
  },
  {
    id: "sub-4",
    userId: "user-1",
    platform: "leetcode",
    problemId: "trapping-rain-water",
    problemTitle: "Trapping Rain Water",
    problemUrl: "https://leetcode.com/problems/trapping-rain-water/",
    difficulty: "HARD",
    tags: ["Array", "Two Pointers", "Dynamic Programming", "Stack"],
    language: "C++",
    status: "ACCEPTED",
    xpEarned: 60,
    submittedAt: new Date(Date.now() - 3600 * 1000 * 48).toISOString(),
  },
  {
    id: "sub-5",
    userId: "user-1",
    platform: "leetcode",
    problemId: "course-schedule",
    problemTitle: "Course Schedule",
    problemUrl: "https://leetcode.com/problems/course-schedule/",
    difficulty: "MEDIUM",
    tags: ["Depth-First Search", "Breadth-First Search", "Graph", "Topological Sort"],
    language: "Python3",
    status: "ACCEPTED",
    xpEarned: 25,
    submittedAt: new Date(Date.now() - 3600 * 1000 * 72).toISOString(),
  },
];

export const INITIAL_SQUADS: Squad[] = [
  {
    id: "squad-1",
    name: "🚀 FAANG Dreamers 2026",
    description: "Nhóm luyện 1 bài mỗi ngày kiên trì chuẩn bị phỏng vấn Big Tech. Ai đứt streak khao cả nhóm 1 ly trà sữa!",
    inviteCode: "FAANG-8899",
    ownerId: "user-1",
    membersCount: 4,
    dailyGoal: 1,
    pledgeRule: "Phạt 25k/ngày nếu quên check-in",
    totalGroupXp: 5420,
    members: [
      {
        userId: "user-1",
        name: "Nguyễn Văn Code (You)",
        avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
        role: "OWNER",
        solvedToday: true,
        todayCount: 2,
        currentStreak: 12,
        weeklyXp: 340,
        lastSolvedTime: "Hôm nay, 14:30",
      },
      {
        userId: "user-2",
        name: "Trần Minh Tech",
        avatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80",
        role: "ADMIN",
        solvedToday: true,
        todayCount: 1,
        currentStreak: 19,
        weeklyXp: 480,
        lastSolvedTime: "Hôm nay, 09:15",
      },
      {
        userId: "user-3",
        name: "Lê Thị Algorithm",
        avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
        role: "MEMBER",
        solvedToday: false,
        todayCount: 0,
        currentStreak: 5,
        weeklyXp: 180,
      },
      {
        userId: "user-4",
        name: "Phạm Hoàng Algo",
        avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
        role: "MEMBER",
        solvedToday: false,
        todayCount: 0,
        currentStreak: 0,
        weeklyXp: 75,
      },
    ],
  },
  {
    id: "squad-2",
    name: "⚔️ Codeforces Div 2 Grinders",
    description: "Cày rating từ Specialist lên Master. Luyện các bài 1200 - 1800 đều đặn hàng tuần.",
    inviteCode: "CF-DIV2-GRIND",
    ownerId: "user-2",
    membersCount: 3,
    dailyGoal: 2,
    pledgeRule: "Giải ít nhất 10 bài/tuần",
    totalGroupXp: 4190,
    members: [
      {
        userId: "user-2",
        name: "Trần Minh Tech",
        avatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80",
        role: "OWNER",
        solvedToday: true,
        todayCount: 1,
        currentStreak: 19,
        weeklyXp: 480,
      },
      {
        userId: "user-1",
        name: "Nguyễn Văn Code (You)",
        avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
        role: "MEMBER",
        solvedToday: true,
        todayCount: 2,
        currentStreak: 12,
        weeklyXp: 340,
      },
    ],
  },
];

export const CURATED_ROADMAPS: CuratedRoadmap[] = [
  {
    id: "blind-75",
    title: "Blind 75 Must-Do",
    description: "Bộ 75 câu hỏi kinh điển nhất cho phỏng vấn thuật toán tại Google, Meta, Amazon.",
    category: "Interview Essentials",
    totalProblems: 75,
    problems: [
      { id: "two-sum", title: "Two Sum", platform: "leetcode", url: "https://leetcode.com/problems/two-sum/", difficulty: "EASY", category: "Arrays & Hashing", order: 1, isSolved: true },
      { id: "best-time-to-buy-and-sell-stock", title: "Best Time to Buy and Sell Stock", platform: "leetcode", url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", difficulty: "EASY", category: "Arrays & Hashing", order: 2, isSolved: true },
      { id: "contains-duplicate", title: "Contains Duplicate", platform: "leetcode", url: "https://leetcode.com/problems/contains-duplicate/", difficulty: "EASY", category: "Arrays & Hashing", order: 3, isSolved: true },
      { id: "product-of-array-except-self", title: "Product of Array Except Self", platform: "leetcode", url: "https://leetcode.com/problems/product-of-array-except-self/", difficulty: "MEDIUM", category: "Arrays & Hashing", order: 4, isSolved: false },
      { id: "maximum-subarray", title: "Maximum Subarray", platform: "leetcode", url: "https://leetcode.com/problems/maximum-subarray/", difficulty: "MEDIUM", category: "Arrays & Hashing", order: 5, isSolved: true },
      { id: "3sum", title: "3Sum", platform: "leetcode", url: "https://leetcode.com/problems/3sum/", difficulty: "MEDIUM", category: "Two Pointers", order: 6, isSolved: false },
      { id: "valid-parentheses", title: "Valid Parentheses", platform: "leetcode", url: "https://leetcode.com/problems/valid-parentheses/", difficulty: "EASY", category: "Stack", order: 7, isSolved: true },
      { id: "merge-two-sorted-lists", title: "Merge Two Sorted Lists", platform: "leetcode", url: "https://leetcode.com/problems/merge-two-sorted-lists/", difficulty: "EASY", category: "Linked List", order: 8, isSolved: true },
      { id: "reverse-linked-list", title: "Reverse Linked List", platform: "leetcode", url: "https://leetcode.com/problems/reverse-linked-list/", difficulty: "EASY", category: "Linked List", order: 9, isSolved: true },
      { id: "lru-cache", title: "LRU Cache", platform: "leetcode", url: "https://leetcode.com/problems/lru-cache/", difficulty: "MEDIUM", category: "Linked List", order: 10, isSolved: true },
      { id: "course-schedule", title: "Course Schedule", platform: "leetcode", url: "https://leetcode.com/problems/course-schedule/", difficulty: "MEDIUM", category: "Graphs", order: 11, isSolved: true },
      { id: "trapping-rain-water", title: "Trapping Rain Water", platform: "leetcode", url: "https://leetcode.com/problems/trapping-rain-water/", difficulty: "HARD", category: "Two Pointers", order: 12, isSolved: true },
      { id: "coin-change", title: "Coin Change", platform: "leetcode", url: "https://leetcode.com/problems/coin-change/", difficulty: "MEDIUM", category: "Dynamic Programming", order: 13, isSolved: false },
      { id: "longest-increasing-subsequence", title: "Longest Increasing Subsequence", platform: "leetcode", url: "https://leetcode.com/problems/longest-increasing-subsequence/", difficulty: "MEDIUM", category: "Dynamic Programming", order: 14, isSolved: false },
    ],
  },
  {
    id: "cf-div2-intro",
    title: "Codeforces Div 2 Starter (800 - 1200)",
    description: "Bộ bài rèn luyện tư duy toán, quy hoạch động cơ bản và kỹ năng triển khai code nhanh.",
    category: "Competitive Programming",
    totalProblems: 20,
    problems: [
      { id: "1850A", title: "To My Critics", platform: "codeforces", url: "https://codeforces.com/problemset/problem/1850/A", difficulty: "EASY", rawDifficulty: "800", category: "Math & Logic", order: 1, isSolved: true },
      { id: "4A", title: "Watermelon", platform: "codeforces", url: "https://codeforces.com/problemset/problem/4/A", difficulty: "EASY", rawDifficulty: "800", category: "Math & Logic", order: 2, isSolved: true },
      { id: "71A", title: "Way Too Long Words", platform: "codeforces", url: "https://codeforces.com/problemset/problem/71/A", difficulty: "EASY", rawDifficulty: "800", category: "String", order: 3, isSolved: true },
      { id: "231A", title: "Team", platform: "codeforces", url: "https://codeforces.com/problemset/problem/231/A", difficulty: "EASY", rawDifficulty: "800", category: "Brute Force", order: 4, isSolved: true },
      { id: "158A", title: "Next Round", platform: "codeforces", url: "https://codeforces.com/problemset/problem/158/A", difficulty: "EASY", rawDifficulty: "800", category: "Arrays", order: 5, isSolved: false },
      { id: "282A", title: "Bit++", platform: "codeforces", url: "https://codeforces.com/problemset/problem/282/A", difficulty: "EASY", rawDifficulty: "800", category: "Implementation", order: 6, isSolved: false },
    ],
  },
];

export const LEADERBOARD_DATA: LeaderboardEntry[] = [
  {
    rank: 1,
    userId: "user-2",
    name: "Trần Minh Tech",
    avatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80",
    handles: [
      { platform: "leetcode", handle: "minhtech_99" },
      { platform: "codeforces", handle: "minh_cf" },
    ],
    currentStreak: 19,
    longestStreak: 35,
    totalSolved: 245,
    weeklyXp: 480,
    totalXp: 3120,
    solvedToday: true,
  },
  {
    rank: 2,
    userId: "user-1",
    name: "Nguyễn Văn Code (You)",
    avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
    handles: [
      { platform: "leetcode", handle: "tourist_lc" },
      { platform: "codeforces", handle: "tourist" },
    ],
    currentStreak: 12,
    longestStreak: 28,
    totalSolved: 227,
    weeklyXp: 340,
    totalXp: 1850,
    solvedToday: true,
  },
  {
    rank: 3,
    userId: "user-5",
    name: "Vũ Bảo Anh",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80",
    handles: [{ platform: "leetcode", handle: "baoanh_algo" }],
    currentStreak: 9,
    longestStreak: 14,
    totalSolved: 110,
    weeklyXp: 260,
    totalXp: 1420,
    solvedToday: true,
  },
  {
    rank: 4,
    userId: "user-3",
    name: "Lê Thị Algorithm",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    handles: [{ platform: "leetcode", handle: "le_algo_girl" }],
    currentStreak: 5,
    longestStreak: 21,
    totalSolved: 98,
    weeklyXp: 180,
    totalXp: 1240,
    solvedToday: false,
  },
  {
    rank: 5,
    userId: "user-4",
    name: "Phạm Hoàng Algo",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    handles: [{ platform: "codeforces", handle: "hoang_coder" }],
    currentStreak: 0,
    longestStreak: 8,
    totalSolved: 45,
    weeklyXp: 75,
    totalXp: 620,
    solvedToday: false,
  },
];
